### ISSUE TITLE
Interested in chatting?

### ISSUE THREAD

**Issue by stevepeak** [Raekye/hmmm#1]
Hi Raekye, first I apologize if reaching out to you via a GH Issue is unwarranted or unwanted, but I felt compelled to say "Hi" 👋 since you are working on language compilers. We use Lark at github.com/storyscript and seeking help to build out the language. If you are interested, I'll be happy to chat more to see if you are interested in contributing, contracting or joining the product development. 

Again, sorry for using this medium for communication, but...had to give it shot! 
Thanks, Steve^

**Comment by Raekye** [comment]
Hi Steve, no worries about contacting me via Github issues haha. I took a look at Storyscript and would be interested in chatting more! I contacted you via the email on your Github profile.
